// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int times = Integer.parseInt(args[0]);
		int moreThen = 0;
		int less = 0;
		double number;
		double ratio;
		for(int i = 0; i < times; i++)
		{
			number = Math.random();
			if (number <= 0.5) {
				less ++;
			}
			else{
				moreThen++;
			}
		}
		
		System.out.println("> 0.5: " + moreThen + " times");
		System.out.println("<= 0.5: " + less + " times");
		
		if(less > 0 && moreThen > 0){
			ratio = (double)moreThen/(double)less;
			System.out.println("Ratio: " + ratio);
		}
	}
}
